// Passo 01 - Sequências Básicas (Atividade 05)
// Nome: Italo Andrade Costa
// 06/07/2026 - Versão 1.0

algoritmo "Sequências Básicas 05"

var
    nota1, nota2, media: Real
inicio
    Escreva ("Nota 1: ")
    Leia (nota1)
    Escreva ("Nota 2: ")
    Leia (nota2)

    media <- (nota1 + nota2)/2
    Escreva ("A média entre ", nota1:2:1, " e ", nota2:2:1, " é igual a ", media:2:1, ".")
fimalgoritmo