// Passo 02 - Condições Básicas (Atividade 18)
// Nome: Italo Andrade Costa
// 08/07/2026 - Versão 1.0

algoritmo "Condições Básicas 18"

var
    idade: Inteiro
inicio
    Escreva ("Qual a sua idade? ")
    Leia (idade)

    Se (idade >= 18) então
        Escreva ("Você possui a idade mínima para votar.")
    senão
        Escreva ("Você não possui a idade mínima para votar.")
    FimSe
fimalgoritmo