// Passo 01 - Sequências Básicas (Atividade 11)
// Nome: Italo Andrade Costa
// 06/07/2026 - Versão 1.0

algoritmo "Sequências Básicas 11"

var
    a, b, c: Inteiro
    delta: Real
inicio
    Escreva ("Digite o valor de a: ")
    Leia (a)
    Escreva ("Digite o valor de b: ")
    Leia (b)
    Escreva ("Digite o valor de c: ")
    Leia (c)

    delta := (b^2)-(4*a*c)

    Escreva ("O valor de Delta é igual a", delta, ".")
fimalgoritmo